[package]
name = "bonding_curves"
version = "0.1.0"
edition = "2024"
description = "A modular Rust library for implementing bonding curves, including Bancor and other types"
license = "MIT"

[dependencies]
fixed = "1.23"
thiserror = "1.0"

[lib]
doctest = false
test = false
